// This file is auto-generated by @hey-api/openapi-ts

export const ActivityLogDetailModelSchema = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        user_uid: {
            type: 'string',
            format: 'uuid',
            title: 'User Uid'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        reference_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reference Type'
        },
        reference_uid: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reference Uid'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        }
    },
    type: 'object',
    required: ['uid', 'user_uid', 'action', 'message', 'created_at'],
    title: 'ActivityLogDetailModel'
} as const;

export const ActivityLogsPublicModelSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ActivityLogDetailModel'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ActivityLogsPublicModel'
} as const;

export const BookSchema = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        author: {
            type: 'string',
            title: 'Author'
        },
        publisher: {
            type: 'string',
            title: 'Publisher'
        },
        published_date: {
            type: 'string',
            format: 'date',
            title: 'Published Date'
        },
        page_count: {
            type: 'integer',
            title: 'Page Count'
        },
        language: {
            type: 'string',
            title: 'Language'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        update_at: {
            type: 'string',
            format: 'date-time',
            title: 'Update At'
        }
    },
    type: 'object',
    required: ['uid', 'title', 'author', 'publisher', 'published_date', 'page_count', 'language', 'created_at', 'update_at'],
    title: 'Book'
} as const;

export const BookCreateModelSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        author: {
            type: 'string',
            title: 'Author'
        },
        publisher: {
            type: 'string',
            title: 'Publisher'
        },
        published_date: {
            type: 'string',
            title: 'Published Date'
        },
        page_count: {
            type: 'integer',
            title: 'Page Count'
        },
        language: {
            type: 'string',
            title: 'Language'
        }
    },
    type: 'object',
    required: ['title', 'author', 'publisher', 'published_date', 'page_count', 'language'],
    title: 'BookCreateModel'
} as const;

export const BookDetailModelSchema = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        author: {
            type: 'string',
            title: 'Author'
        },
        publisher: {
            type: 'string',
            title: 'Publisher'
        },
        published_date: {
            type: 'string',
            format: 'date',
            title: 'Published Date'
        },
        page_count: {
            type: 'integer',
            title: 'Page Count'
        },
        language: {
            type: 'string',
            title: 'Language'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        update_at: {
            type: 'string',
            format: 'date-time',
            title: 'Update At'
        },
        reviews: {
            items: {
                '$ref': '#/components/schemas/ReviewModel'
            },
            type: 'array',
            title: 'Reviews'
        },
        tags: {
            items: {
                '$ref': '#/components/schemas/TagModel'
            },
            type: 'array',
            title: 'Tags'
        }
    },
    type: 'object',
    required: ['uid', 'title', 'author', 'publisher', 'published_date', 'page_count', 'language', 'created_at', 'update_at', 'reviews', 'tags'],
    title: 'BookDetailModel'
} as const;

export const BookUpdateModelSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        author: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author'
        },
        publisher: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Publisher'
        },
        page_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Count'
        },
        language: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language'
        }
    },
    type: 'object',
    title: 'BookUpdateModel'
} as const;

export const CategoriesPublicModelSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CategoryModel'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CategoriesPublicModel'
} as const;

export const CategoryCreateModelSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CategoryCreateModel'
} as const;

export const CategoryModelSchema = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        user_uid: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Uid'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        update_at: {
            type: 'string',
            format: 'date-time',
            title: 'Update At'
        }
    },
    type: 'object',
    required: ['uid', 'name', 'description', 'user_uid', 'created_at', 'update_at'],
    title: 'CategoryModel'
} as const;

export const CategoryUpdateModelSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'CategoryUpdateModel'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IngredientsTreeResponseSchema = {
    properties: {
        root: {
            '$ref': '#/components/schemas/RecipeTreeNode'
        }
    },
    type: 'object',
    required: ['root'],
    title: 'IngredientsTreeResponse'
} as const;

export const InventoryCreateModelSchema = {
    properties: {
        item_uid: {
            type: 'string',
            format: 'uuid',
            title: 'Item Uid'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity',
            default: 1
        }
    },
    type: 'object',
    required: ['item_uid'],
    title: 'InventoryCreateModel'
} as const;

export const InventoryItemModelSchema = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        user_uid: {
            type: 'string',
            format: 'uuid',
            title: 'User Uid'
        },
        item_uid: {
            type: 'string',
            format: 'uuid',
            title: 'Item Uid'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['uid', 'user_uid', 'item_uid', 'quantity', 'created_at'],
    title: 'InventoryItemModel'
} as const;

export const InventoryPublicModelSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InventoryItemModel'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InventoryPublicModel'
} as const;

export const InventoryUpdateModelSchema = {
    properties: {
        quantity: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quantity'
        }
    },
    type: 'object',
    title: 'InventoryUpdateModel'
} as const;

export const ItemCreateModelSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        rarity: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rarity'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        max_drop: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Drop'
        },
        type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        chi: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chi'
        },
        texture_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Texture Type'
        },
        collision_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Collision Type'
        },
        seed_color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seed Color'
        },
        grow_time: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grow Time'
        },
        default_gems_drop: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Gems Drop'
        },
        hits_with_hand: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hits With Hand'
        },
        hits_with_pickaxe: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hits With Pickaxe'
        },
        restore_time_seconds: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Restore Time Seconds'
        },
        scraped: {
            type: 'boolean',
            title: 'Scraped',
            default: false
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ItemCreateModel'
} as const;

export const ItemLinkCreateModelSchema = {
    properties: {
        source_uid: {
            type: 'string',
            format: 'uuid',
            title: 'Source Uid'
        },
        target_uid: {
            type: 'string',
            format: 'uuid',
            title: 'Target Uid'
        }
    },
    type: 'object',
    required: ['source_uid', 'target_uid'],
    title: 'ItemLinkCreateModel'
} as const;

export const ItemLinkModelSchema = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        source_uid: {
            type: 'string',
            format: 'uuid',
            title: 'Source Uid'
        },
        target_uid: {
            type: 'string',
            format: 'uuid',
            title: 'Target Uid'
        }
    },
    type: 'object',
    required: ['uid', 'source_uid', 'target_uid'],
    title: 'ItemLinkModel'
} as const;

export const ItemModelSchema = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        rarity: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rarity'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        max_drop: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Drop'
        },
        type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        chi: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chi'
        },
        texture_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Texture Type'
        },
        collision_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Collision Type'
        },
        seed_color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seed Color'
        },
        grow_time: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grow Time'
        },
        default_gems_drop: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Gems Drop'
        },
        hits_with_hand: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hits With Hand'
        },
        hits_with_pickaxe: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hits With Pickaxe'
        },
        restore_time_seconds: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Restore Time Seconds'
        },
        scraped: {
            type: 'boolean',
            title: 'Scraped',
            default: false
        },
        created_by_uid: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By Uid'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        update_at: {
            type: 'string',
            format: 'date-time',
            title: 'Update At'
        }
    },
    type: 'object',
    required: ['uid', 'name', 'created_at', 'update_at'],
    title: 'ItemModel'
} as const;

export const ItemUpdateModelSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        rarity: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rarity'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        max_drop: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Drop'
        },
        type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        chi: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chi'
        },
        texture_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Texture Type'
        },
        collision_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Collision Type'
        },
        seed_color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seed Color'
        },
        grow_time: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grow Time'
        },
        default_gems_drop: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Gems Drop'
        },
        hits_with_hand: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hits With Hand'
        },
        hits_with_pickaxe: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hits With Pickaxe'
        },
        restore_time_seconds: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Restore Time Seconds'
        },
        scraped: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scraped'
        }
    },
    type: 'object',
    title: 'ItemUpdateModel'
} as const;

export const ItemsPublicModelSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemModel'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublicModel'
} as const;

export const MassCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        mode: {
            type: 'string',
            title: 'Mode',
            default: 'a'
        },
        target_seeds: {
            type: 'integer',
            title: 'Target Seeds',
            default: 0
        },
        hit_cost: {
            type: 'integer',
            title: 'Hit Cost',
            default: 1
        },
        items: {
            items: {
                '$ref': '#/components/schemas/MassItemInput'
            },
            type: 'array',
            title: 'Items',
            default: []
        }
    },
    type: 'object',
    required: ['name'],
    title: 'MassCreate'
} as const;

export const MassItemInputSchema = {
    properties: {
        item_uid: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Uid'
        },
        item_name: {
            type: 'string',
            title: 'Item Name',
            default: 'Item'
        },
        tree_rarity: {
            type: 'integer',
            title: 'Tree Rarity',
            default: 1
        },
        max_blocks: {
            type: 'integer',
            title: 'Max Blocks',
            default: 1
        },
        jumlah_pohon: {
            type: 'integer',
            title: 'Jumlah Pohon',
            default: 0
        },
        price: {
            type: 'integer',
            title: 'Price',
            default: 0
        },
        is_fuel: {
            type: 'boolean',
            title: 'Is Fuel',
            default: false
        },
        is_auto_break: {
            type: 'boolean',
            title: 'Is Auto Break',
            default: false
        },
        source_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Path'
        }
    },
    type: 'object',
    title: 'MassItemInput'
} as const;

export const MassItemResultSchema = {
    properties: {
        item_uid: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Uid'
        },
        item_name: {
            type: 'string',
            title: 'Item Name',
            default: 'Item'
        },
        tree_rarity: {
            type: 'integer',
            title: 'Tree Rarity',
            default: 1
        },
        max_blocks: {
            type: 'integer',
            title: 'Max Blocks',
            default: 1
        },
        jumlah_pohon: {
            type: 'integer',
            title: 'Jumlah Pohon',
            default: 0
        },
        price: {
            type: 'integer',
            title: 'Price',
            default: 0
        },
        is_fuel: {
            type: 'boolean',
            title: 'Is Fuel',
            default: false
        },
        is_auto_break: {
            type: 'boolean',
            title: 'Is Auto Break',
            default: false
        },
        source_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Path'
        },
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        blok_yielded: {
            type: 'integer',
            title: 'Blok Yielded'
        },
        total_smash_efektif: {
            type: 'integer',
            title: 'Total Smash Efektif'
        },
        seeds_fallen: {
            type: 'integer',
            title: 'Seeds Fallen'
        },
        seeds_from_smash: {
            type: 'integer',
            title: 'Seeds From Smash'
        },
        total_seeds_return: {
            type: 'integer',
            title: 'Total Seeds Return'
        },
        seed_return_rate: {
            type: 'number',
            title: 'Seed Return Rate'
        },
        gem_blocks: {
            type: 'integer',
            title: 'Gem Blocks'
        },
        avg_gems_per_block: {
            type: 'number',
            title: 'Avg Gems Per Block'
        },
        harvest_gems: {
            type: 'integer',
            title: 'Harvest Gems'
        },
        total_gems_didapat: {
            type: 'integer',
            title: 'Total Gems Didapat'
        },
        grow_time_seconds: {
            type: 'integer',
            title: 'Grow Time Seconds'
        },
        grow_time_readable: {
            type: 'string',
            title: 'Grow Time Readable',
            default: ''
        }
    },
    type: 'object',
    required: ['uid', 'blok_yielded', 'total_smash_efektif', 'seeds_fallen', 'seeds_from_smash', 'total_seeds_return', 'seed_return_rate', 'gem_blocks', 'avg_gems_per_block', 'harvest_gems', 'total_gems_didapat', 'grow_time_seconds'],
    title: 'MassItemResult'
} as const;

export const MassModelSchema = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        mode: {
            type: 'string',
            title: 'Mode'
        },
        target_seeds: {
            type: 'integer',
            title: 'Target Seeds',
            default: 0
        },
        hit_cost: {
            type: 'integer',
            title: 'Hit Cost',
            default: 1
        },
        user_uid: {
            type: 'string',
            format: 'uuid',
            title: 'User Uid'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        update_at: {
            type: 'string',
            format: 'date-time',
            title: 'Update At'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/MassItemResult'
            },
            type: 'array',
            title: 'Items',
            default: []
        }
    },
    type: 'object',
    required: ['uid', 'name', 'mode', 'user_uid', 'created_at', 'update_at'],
    title: 'MassModel'
} as const;

export const MassUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        mode: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mode'
        },
        target_seeds: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Seeds'
        },
        hit_cost: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hit Cost'
        },
        items: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/MassItemInput'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Items'
        }
    },
    type: 'object',
    title: 'MassUpdate'
} as const;

export const MassesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MassModel'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MassesPublic'
} as const;

export const PossibilitiesResponseSchema = {
    properties: {
        possibilities: {
            items: {
                '$ref': '#/components/schemas/ItemModel'
            },
            type: 'array',
            title: 'Possibilities'
        }
    },
    type: 'object',
    required: ['possibilities'],
    title: 'PossibilitiesResponse'
} as const;

export const RecipeTreeNodeSchema = {
    properties: {
        item: {
            '$ref': '#/components/schemas/ItemModel'
        },
        ingredients: {
            items: {
                '$ref': '#/components/schemas/RecipeTreeNode'
            },
            type: 'array',
            title: 'Ingredients',
            default: []
        }
    },
    type: 'object',
    required: ['item'],
    title: 'RecipeTreeNode'
} as const;

export const ReviewCreateModelSchema = {
    properties: {
        rating: {
            type: 'integer',
            exclusiveMaximum: 5,
            title: 'Rating'
        },
        review_text: {
            type: 'string',
            title: 'Review Text'
        }
    },
    type: 'object',
    required: ['rating', 'review_text'],
    title: 'ReviewCreateModel'
} as const;

export const ReviewModelSchema = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        rating: {
            type: 'integer',
            exclusiveMaximum: 5,
            title: 'Rating'
        },
        review_text: {
            type: 'string',
            title: 'Review Text'
        },
        user_uid: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Uid'
        },
        book_uid: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Book Uid'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        update_at: {
            type: 'string',
            format: 'date-time',
            title: 'Update At'
        }
    },
    type: 'object',
    required: ['uid', 'rating', 'review_text', 'user_uid', 'book_uid', 'created_at', 'update_at'],
    title: 'ReviewModel'
} as const;

export const TagAddModelSchema = {
    properties: {
        tags: {
            items: {
                '$ref': '#/components/schemas/TagCreateModel'
            },
            type: 'array',
            title: 'Tags'
        }
    },
    type: 'object',
    required: ['tags'],
    title: 'TagAddModel'
} as const;

export const TagCreateModelSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'TagCreateModel'
} as const;

export const TagModelSchema = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['uid', 'name', 'created_at'],
    title: 'TagModel'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        old_password: {
            type: 'string',
            title: 'Old Password'
        },
        new_password: {
            type: 'string',
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['old_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserSchema = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        update_at: {
            type: 'string',
            format: 'date-time',
            title: 'Update At'
        }
    },
    type: 'object',
    required: ['uid', 'username', 'first_name', 'last_name', 'email', 'role', 'is_verified', 'is_superuser', 'is_active', 'created_at', 'update_at'],
    title: 'User'
} as const;

export const UserCreateSchema = {
    properties: {
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        role: {
            type: 'string',
            title: 'Role',
            default: 'user'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserLoginModelSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 40,
            title: 'Email'
        },
        password: {
            type: 'string',
            minLength: 6,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserLoginModel'
} as const;

export const UserRegisterResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        user: {
            additionalProperties: true,
            type: 'object',
            title: 'User'
        }
    },
    type: 'object',
    required: ['message', 'user'],
    title: 'UserRegisterResponse'
} as const;

export const UserUpdateSchema = {
    properties: {
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        role: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicModelSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/User'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublicModel'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;