// This file is auto-generated by @hey-api/openapi-ts

export type ActivityLogDetailModel = {
    uid: string;
    user_uid: string;
    action: string;
    reference_type?: (string | null);
    reference_uid?: (string | null);
    message: string;
    created_at: string;
    data?: ({
    [key: string]: unknown;
} | null);
};

export type ActivityLogsPublicModel = {
    data: Array<ActivityLogDetailModel>;
    count: number;
};

export type Book = {
    uid: string;
    title: string;
    author: string;
    publisher: string;
    published_date: string;
    page_count: number;
    language: string;
    created_at: string;
    update_at: string;
};

export type BookCreateModel = {
    title: string;
    author: string;
    publisher: string;
    published_date: string;
    page_count: number;
    language: string;
};

export type BookDetailModel = {
    uid: string;
    title: string;
    author: string;
    publisher: string;
    published_date: string;
    page_count: number;
    language: string;
    created_at: string;
    update_at: string;
    reviews: Array<ReviewModel>;
    tags: Array<TagModel>;
};

export type BookUpdateModel = {
    title?: (string | null);
    author?: (string | null);
    publisher?: (string | null);
    page_count?: (number | null);
    language?: (string | null);
};

export type CategoriesPublicModel = {
    data: Array<CategoryModel>;
    count: number;
};

export type CategoryCreateModel = {
    name: string;
    description?: (string | null);
};

export type CategoryModel = {
    uid: string;
    name: string;
    description: (string | null);
    user_uid: (string | null);
    created_at: string;
    update_at: string;
};

export type CategoryUpdateModel = {
    name?: (string | null);
    description?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IngredientsTreeResponse = {
    root: RecipeTreeNode;
};

export type InventoryCreateModel = {
    item_uid: string;
    quantity?: number;
};

export type InventoryItemModel = {
    uid: string;
    user_uid: string;
    item_uid: string;
    quantity: number;
    created_at: string;
};

export type InventoryPublicModel = {
    data: Array<InventoryItemModel>;
    count: number;
};

export type InventoryUpdateModel = {
    quantity?: (number | null);
};

export type ItemCreateModel = {
    name: string;
    rarity?: (string | null);
    description?: (string | null);
    max_drop?: (number | null);
    type?: (string | null);
    chi?: (string | null);
    texture_type?: (string | null);
    collision_type?: (string | null);
    seed_color?: (string | null);
    grow_time?: (number | null);
    default_gems_drop?: (string | null);
    hits_with_hand?: (number | null);
    hits_with_pickaxe?: (number | null);
    restore_time_seconds?: (number | null);
    scraped?: boolean;
};

export type ItemLinkCreateModel = {
    source_uid: string;
    target_uid: string;
};

export type ItemLinkModel = {
    uid: string;
    source_uid: string;
    target_uid: string;
};

export type ItemModel = {
    uid: string;
    name: string;
    rarity?: (string | null);
    description?: (string | null);
    max_drop?: (number | null);
    type?: (string | null);
    chi?: (string | null);
    texture_type?: (string | null);
    collision_type?: (string | null);
    seed_color?: (string | null);
    grow_time?: (number | null);
    default_gems_drop?: (string | null);
    hits_with_hand?: (number | null);
    hits_with_pickaxe?: (number | null);
    restore_time_seconds?: (number | null);
    scraped?: boolean;
    created_by_uid?: (string | null);
    created_at: string;
    update_at: string;
};

export type ItemsPublicModel = {
    data: Array<ItemModel>;
    count: number;
};

export type ItemUpdateModel = {
    name?: (string | null);
    rarity?: (string | null);
    description?: (string | null);
    max_drop?: (number | null);
    type?: (string | null);
    chi?: (string | null);
    texture_type?: (string | null);
    collision_type?: (string | null);
    seed_color?: (string | null);
    grow_time?: (number | null);
    default_gems_drop?: (string | null);
    hits_with_hand?: (number | null);
    hits_with_pickaxe?: (number | null);
    restore_time_seconds?: (number | null);
    scraped?: (boolean | null);
};

export type MassCreate = {
    name: string;
    description?: (string | null);
    mode?: string;
    target_seeds?: number;
    hit_cost?: number;
    gems_per_wl?: number;
    items?: Array<MassItemInput>;
};

export type MassesPublic = {
    data: Array<MassModel>;
    count: number;
};

export type MassItemInput = {
    item_uid?: (string | null);
    item_name?: string;
    rarity?: string;
    tree_rarity?: number;
    max_blocks?: number;
    jumlah_pohon?: number;
    price_buy?: number;
    price_sell?: number;
    is_fuel?: boolean;
    is_auto_break?: boolean;
    source_path?: (string | null);
};

export type MassItemResult = {
    item_uid?: (string | null);
    item_name?: string;
    rarity?: string;
    tree_rarity?: number;
    max_blocks?: number;
    jumlah_pohon?: number;
    price_buy?: number;
    price_sell?: number;
    is_fuel?: boolean;
    is_auto_break?: boolean;
    source_path?: (string | null);
    uid: string;
    blok_yielded: number;
    total_smash_efektif: number;
    seeds_fallen: number;
    seeds_from_smash: number;
    total_seeds_return: number;
    seed_return_rate: number;
    gem_blocks: number;
    avg_gems_per_block: number;
    harvest_gems: number;
    total_gems_didapat: number;
    grow_time_seconds: number;
    grow_time_readable?: string;
};

export type MassModel = {
    uid: string;
    name: string;
    description?: (string | null);
    mode: string;
    target_seeds?: number;
    hit_cost?: number;
    gems_per_wl?: number;
    user_uid: string;
    created_at: string;
    update_at: string;
    items?: Array<MassItemResult>;
};

export type MassUpdate = {
    name?: (string | null);
    description?: (string | null);
    mode?: (string | null);
    target_seeds?: (number | null);
    hit_cost?: (number | null);
    gems_per_wl?: (number | null);
    items?: (Array<MassItemInput> | null);
};

export type PossibilitiesResponse = {
    possibilities: Array<ItemModel>;
};

export type RecipeTreeNode = {
    item: ItemModel;
    ingredients?: Array<RecipeTreeNode>;
};

export type ReviewCreateModel = {
    rating: number;
    review_text: string;
};

export type ReviewModel = {
    uid: string;
    rating: number;
    review_text: string;
    user_uid: (string | null);
    book_uid: (string | null);
    created_at: string;
    update_at: string;
};

export type TagAddModel = {
    tags: Array<TagCreateModel>;
};

export type TagCreateModel = {
    name: string;
};

export type TagModel = {
    uid: string;
    name: string;
    created_at: string;
};

export type UpdatePassword = {
    old_password: string;
    new_password: string;
};

export type User = {
    uid: string;
    username: string;
    first_name: string;
    last_name: string;
    email: string;
    role: string;
    is_verified: boolean;
    is_superuser: boolean;
    is_active: boolean;
    created_at: string;
    update_at: string;
};

export type UserCreate = {
    first_name?: (string | null);
    last_name?: (string | null);
    username?: (string | null);
    email: string;
    password: string;
    role?: string;
    is_superuser?: boolean;
    is_active?: boolean;
};

export type UserLoginModel = {
    email: string;
    password: string;
};

export type UserRegisterResponse = {
    message: string;
    user: {
        [key: string]: unknown;
    };
};

export type UsersPublicModel = {
    data: Array<User>;
    count: number;
};

export type UserUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    username?: (string | null);
    email?: (string | null);
    role?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    first_name?: (string | null);
    last_name?: (string | null);
    username?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadActivityLogsData = {
    limit?: number;
    skip?: number;
};

export type ReadActivityLogsResponse = (ActivityLogsPublicModel);

export type RegisterUserData = {
    requestBody: UserCreate;
};

export type RegisterUserResponse = (UserRegisterResponse);

export type VerifyUserAccountApiV1AuthVerifyTokenGetData = {
    token: string;
};

export type VerifyUserAccountApiV1AuthVerifyTokenGetResponse = (unknown);

export type GetNewAccessTokenApiV1AuthRefreshTokenGetResponse = (unknown);

export type LogoutResponse = (unknown);

export type ReadBooksResponse = (Array<Book>);

export type CreateBookData = {
    requestBody: BookCreateModel;
};

export type CreateBookResponse = (Book);

export type ReadUserSubmissionsData = {
    userUid: string;
};

export type ReadUserSubmissionsResponse = (Array<Book>);

export type ReadBookData = {
    bookUid: string;
};

export type ReadBookResponse = (BookDetailModel);

export type UpdateBookData = {
    bookUid: string;
    requestBody: BookUpdateModel;
};

export type UpdateBookResponse = (Book);

export type DeleteBookData = {
    bookUid: string;
};

export type DeleteBookResponse = (void);

export type ReadCategoriesData = {
    limit?: number;
    skip?: number;
};

export type ReadCategoriesResponse = (CategoriesPublicModel);

export type CreateCategoryData = {
    requestBody: CategoryCreateModel;
};

export type CreateCategoryResponse = (CategoryModel);

export type ReadCategoryData = {
    categoryUid: string;
};

export type ReadCategoryResponse = (CategoryModel);

export type UpdateCategoryData = {
    categoryUid: string;
    requestBody: CategoryUpdateModel;
};

export type UpdateCategoryResponse = (CategoryModel);

export type DeleteCategoryData = {
    categoryUid: string;
};

export type DeleteCategoryResponse = (void);

export type ReadInventoryData = {
    limit?: number;
    skip?: number;
};

export type ReadInventoryResponse = (InventoryPublicModel);

export type AddToInventoryData = {
    requestBody: InventoryCreateModel;
};

export type AddToInventoryResponse = (InventoryItemModel);

export type UpdateInventoryItemData = {
    itemUid: string;
    requestBody: InventoryUpdateModel;
};

export type UpdateInventoryItemResponse = (InventoryItemModel);

export type DeleteFromInventoryData = {
    itemUid: string;
};

export type DeleteFromInventoryResponse = (void);

export type ReadItemsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type ReadItemsResponse = (ItemsPublicModel);

export type CreateItemData = {
    requestBody: ItemCreateModel;
};

export type CreateItemResponse = (ItemModel);

export type ReadItemData = {
    itemUid: string;
};

export type ReadItemResponse = (ItemModel);

export type UpdateItemData = {
    itemUid: string;
    requestBody: ItemUpdateModel;
};

export type UpdateItemResponse = (ItemModel);

export type DeleteItemData = {
    itemUid: string;
};

export type DeleteItemResponse = (void);

export type ReadItemIngredientsData = {
    itemUid: string;
};

export type ReadItemIngredientsResponse = (IngredientsTreeResponse);

export type ReadItemPossibilitiesData = {
    itemUid: string;
};

export type ReadItemPossibilitiesResponse = (PossibilitiesResponse);

export type CreateItemLinkData = {
    requestBody: ItemLinkCreateModel;
};

export type CreateItemLinkResponse = (ItemLinkModel);

export type DeleteItemLinkData = {
    linkUid: string;
};

export type DeleteItemLinkResponse = (void);

export type LoginAccessTokenData = {
    requestBody: UserLoginModel;
};

export type LoginAccessTokenResponse = ({
    [key: string]: unknown;
});

export type ReadMassesData = {
    limit?: number;
    skip?: number;
};

export type ReadMassesResponse = (MassesPublic);

export type CreateMassData = {
    requestBody: MassCreate;
};

export type CreateMassResponse = (MassModel);

export type ReadMassData = {
    massUid: string;
};

export type ReadMassResponse = (MassModel);

export type UpdateMassData = {
    massUid: string;
    requestBody: MassUpdate;
};

export type UpdateMassResponse = (MassModel);

export type DeleteMassData = {
    massUid: string;
};

export type DeleteMassResponse = (void);

export type CalculateMassData = {
    massUid: string;
};

export type CalculateMassResponse = (MassModel);

export type ReadReviewsResponse = (unknown);

export type ReadReviewData = {
    reviewUid: string;
};

export type ReadReviewResponse = (unknown);

export type DeleteReviewData = {
    reviewUid: string;
};

export type DeleteReviewResponse = (void);

export type CreateReviewData = {
    bookUid: string;
    requestBody: ReviewCreateModel;
};

export type CreateReviewResponse = (unknown);

export type ReadTagsResponse = (Array<TagModel>);

export type CreateTagData = {
    requestBody: TagCreateModel;
};

export type CreateTagResponse = (TagModel);

export type AddTagsToBookData = {
    bookUid: string;
    requestBody: TagAddModel;
};

export type AddTagsToBookResponse = (Book);

export type UpdateTagData = {
    requestBody: TagCreateModel;
    tagUid: string;
};

export type UpdateTagResponse = (TagModel);

export type DeleteTagData = {
    tagUid: string;
};

export type DeleteTagResponse = (void);

export type ReadUserMeResponse = (User);

export type DeleteUserMeResponse = (void);

export type UpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UpdateUserMeResponse = (User);

export type UpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UpdatePasswordMeResponse = (void);

export type ReadUsersData = {
    limit?: number;
    skip?: number;
};

export type ReadUsersResponse = (UsersPublicModel);

export type CreateUserData = {
    requestBody: UserCreate;
};

export type CreateUserResponse = (User);

export type UpdateUserData = {
    requestBody: UserUpdate;
    userUid: string;
};

export type UpdateUserResponse = (User);

export type DeleteUserData = {
    userUid: string;
};

export type DeleteUserResponse = (void);