"""add price fuel auto_break hit_cost

Revision ID: 4cf8d3b66d46
Revises: c6ae8e13af00
Create Date: 2026-06-05 17:38:21.490689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4cf8d3b66d46'
down_revision: Union[str, None] = 'c6ae8e13af00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('mass_items', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('mass_items', sa.Column('is_fuel', sa.Boolean(), nullable=True))
    op.add_column('mass_items', sa.Column('is_auto_break', sa.Boolean(), nullable=True))
    op.execute("UPDATE mass_items SET price = 0 WHERE price IS NULL")
    op.execute("UPDATE mass_items SET is_fuel = false WHERE is_fuel IS NULL")
    op.execute("UPDATE mass_items SET is_auto_break = false WHERE is_auto_break IS NULL")
    op.alter_column('mass_items', 'price', nullable=False)
    op.alter_column('mass_items', 'is_fuel', nullable=False)
    op.alter_column('mass_items', 'is_auto_break', nullable=False)
    op.add_column('masses', sa.Column('hit_cost', sa.Integer(), nullable=True))
    op.execute("UPDATE masses SET hit_cost = 1 WHERE hit_cost IS NULL")
    op.alter_column('masses', 'hit_cost', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masses', 'hit_cost')
    op.drop_column('mass_items', 'is_auto_break')
    op.drop_column('mass_items', 'is_fuel')
    op.drop_column('mass_items', 'price')
    # ### end Alembic commands ###
