"""add source_path to mass_item

Revision ID: c6ae8e13af00
Revises: 7b08fb17637f
Create Date: 2026-06-05 17:12:57.544414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6ae8e13af00'
down_revision: Union[str, None] = '7b08fb17637f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mass_items', sa.Column('source_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mass_items', 'source_path')
    # ### end Alembic commands ###
